### ISSUE TITLE
Acolytes can be Infested

### ISSUE THREAD

**Issue by arden-arteles** [klipsey/SeamstressMod#3]
More a suggestion than a bug -- acolytes probably shouldn't be able to be infested. Their homing attacks and shaman's low damage output highly disincentivize playing with SotV enabled. Had a run end suddenly due to that a little earlier, and I don't think there was really anything I could do about it.

**Comment by klipsey** [comment]
what the hell is an acolyte

**Comment by MagentaLizard** [comment]
WRONG MOD LMAO
